### ISSUE TITLE
How to use route mixin within component

### ISSUE THREAD

**Issue by richardvenneman** [hhff/ember-infinity#136]
Hello,

I'm trying to use ember-infinite within component instead of a route. I left a comment on #108 (which I deleted) but thought that a new issue would be more appropriate.

As per @kellyselden's comment, I searched for a way to load the model without the `model()` hook (which is only executed on routes). I thought `didRender()` would be a good place.

This is the component code:

```javascript
import Ember from 'ember';
import InfinityRoute from 'ember-infinity/mixins/route';

export default Ember.Component.extend(InfinityRoute, {
  store: Ember.inject.service(),
  
  perPageParam: 'page[size]',
  pageParam: 'page[number]',
  totalPagesParam: 'meta.page_total',

  didRender() {
    this.infinityModel('booking', {
      perPage: 8,
      startingPage: 1,
    });
  }
});
```

A network call is being made but no data is rendered and I'm left staring at the "Loading Infinite Model..." message. I couldn't get it to work with this and other approaches I tried. I scourging the source and tried to make sense of it all, but I guess I'm still too new to Ember.

Perhaps I should use the `modelPath` option?

- Ember: 2.3.0
- Ember Data: 2.3.3
- ember-infinity: 0.2.1

**Comment by hhff** [comment]
Yup!  You'll need model path to correspond to where your infinityModel lives inside of your component.  It's set by default to `controller.model`, which doesn't exist in the component context.

I would also recommend using `didInitAttrs` or `didReceiveAttrs` rather than `didRender`.

**Note:** Unrelated to Ember Infinity itself, I wouldn't actually advise an approach like this.  By doing this - you're creating a "state tree" in your application that is isolated to the component.  That's an immutability anti-pattern - your component can now modify the state of the store independent of it's route (the piece of Ember which is primarily concerned with loading data).

That's the reason why Components can't access the store by default.

**Comment by richardvenneman** [comment]
Thanks for the quick reply and great side note @hhff :raised_hands: I'm all for best practises of course. Learned new stuff, ended up refactoring a bit and everything works great now :)

**Comment by hhff** [comment]
nice!!

**Comment by DWC01** [comment]
Hey @richardvenneman , would you mind sharing what you updated the `modelPath` to in order to get ember-infinite to work inside a component (or any other changes you made)? I am currently at the same spot as you were in your initial comment, and struggling to get the rest working past that point. Any help pointing in the right direction would be much appreciated! Thanks!

**Comment by richardvenneman** [comment]
@DWC01 I'm afraid it's been a while since I touched the app's Ember codebase (and haven't been doing much Ember lately). From what I remember I indeed refactored the component code to be able to use the `model()` hook in the controller. It looks something like this:

Template:
```handlebars
{{#each model as |booking|}}
  {{booking-listing booking=booking}}
{{/each}}

{{#infinity-loader infinityModel=model triggerOffset=200}}
  {{loading-indicator}}
{{/infinity-loader}}
```

Route:
```javascript
export default Ember.Route.extend(AuthenticatedRouteMixin, InfinityRoute, {
  perPageParam: 'page[size]',
  pageParam: 'page[number]',
  totalPagesParam: 'meta.page_total',

  model() {
    return this.infinityModel('booking', {
      perPage: 8,
      startingPage: 1,
      order: 'desc'
    });
  }
});
```

**Comment by The-Don-Himself** [comment]
@DWC01 Did you get it to work within a component?
@hhff Is there a working example of this? I know it's anti-pattern but if its possible a documented example would be nice. For example, say you're showcasing a blog post and a reader is reading down a list of comments, I think it would be fantastic to display a component on the left that displays 5 related posts, then if the comment thread is long and as the user shows interest by scrolling down, another 5 and so on. In cases where the related data cannot be fetched during the route model(), I think this would be a nice feature, or how would you propose?

**Comment by hhff** [comment]
Hi @The-Don-Himself - the only documentation I'd be willing to add would be to the effect of "don't use the mixin in a component, it's not supported".

You don't necessarily need to use the `model()` hook to instantiate the infinityModel.  Something like this could work:

```
Route.extend({
  ...snip
  actions: {
    userDidOpenCommentThread(post_id) {
      set(this, 'controller.currentCommentThreadInfinityModel', this.infinityModel('comment', {
        perPage: 5,
        startingPage: 1,
        modelPath: 'controller.currentCommentThreadInfinityModel'
      });
    }
  }
})
```

then in you template:

```
{{post-card post=post}}

{{#if currentCommentThreadInfinityModel}}
  {{#each currentCommentThreadInfinityModel as |comment|}}
    {{comment-card comment=comment}}
  {{/each}}
  {{infinity-loader infinityModel=currentCommentThreadInfinityModel}}
{{else}}
  <button {{action (route-action 'userDidOpenCommentThread' post.id)}}>Open Comments</button>
{{/if}}
```

However - to address the problem of Multiple infinity models on a single route - I'm working on that.  It's functional, but has broken all of tests.  Coming soon...!

**Comment by The-Don-Himself** [comment]
Hi @hhff 
Thanks for your reply and suggestion, I really wanted to respond to it sooner. I actually dint know that it's not a must to tie it down to the route's model. I thus agree that that may be a much better way. I've tried your way and while a request is made to the backend, nothing renders on the front, replacing
````
this.infinityModel('comment', {
````
with a regular model renders the content so I'm thinking it must be some infinity config, maybe modelPath parameter but it's like for like with what you wrote unless something is mistaken.

Just as a by the way, you might have slightly misunderstood my sample, a lot of content apps like Medium display related articles at the end of a blog post (after all comments). What I am thinking is that as infinite scroll of related articles (eg to a segment/sidebar on your right) as your read through the blog and comments might be nice. Giving the user a better chance at actually clicking on one of them. Because a user can lose interest in an article midway but would have seen maybe 1 or 2 of interest from the ember-infinity. For this reason, it only makes sense to load if after the model and route transition hence why my earlier suggestion.

**Comment by hhff** [comment]
ok @The-Don-Himself !  I wish i could be more help, but we mostly use github for bug reports.  I'd suggest opening an issue on stack overflow!

**Comment by The-Don-Himself** [comment]
@hhff Again, thanks for the response. I'm sure you meant it in good faith, but I already know SO is for Q/A and Github for issues/bugs/feature requests/etc.

I'm not creating a blog but thought I could use it as an example to sway your thinking for ember-infinity within a component... kinda like this post on Ember Igniter https://emberigniter.com/should-components-load-data/ where they use a twitter feed as an example, I don't think they meant to seek support to actually load a twitter feed.

I did report back though, that the alternative solution you provided (to loading as a component) wasn't working, at least not as you provided. I'll investigate further the best way forward. Thanks for the add-on :+1:

**Comment by hhff** [comment]
happy to help!
