### ISSUE TITLE
Using websockets to insert new records

### ISSUE THREAD

**Issue by daniel-de-wit** [hhff/ember-infinity#149]
I receive JSONAPI payload from a websocket which I normalise and insert into the store, like so:

Route ( with InfinityRoute mixin ):
```
createChatMessage(JSONApiPayload) {
  const store = this.get('store');
  const record =  store.push(store.normalize('chat-message', JSONApiPayload));

  // Update the infinityModel with the new record..
}
```
How should I insert this new record into the infinityModel ( properly )?

For now I extended the ember-infinity mixin with 2 public methods:
```
  pushRecord(record) {
    const infinityModel = this._infinityModel();

    infinityModel.pushObject(record._internalModel);
  },

  pushRecords(records) {
    records.forEach(record => {
      this.pushRecord(record);
    });
  }
```
Which I found in the open PR: https://github.com/hhff/ember-infinity/pull/107

Then in my route I added the call to pushRecord like so:
```
createChatMessage(JSONApiPayload) {
  const store = this.get('store');
  const record = store.push(store.normalize('chat-message', JSONApiPayload));

  this.pushRecord(record);
}
```

My quick solution works, but there must be a better way? Any help on this would be greatly appreciated.

**Comment by hhff** [comment]
HI @daniel-de-wit - yeah I agree - this isn't ideal.

We currently do this:
```return infinityModel.pushObjects(newObjects.get('content'));```

Which I don't love.

Currently all the methods that Ember Infinity use to populate the `infinityModel` are private - that's mostly by design, but we for sure need a more "supported" way for users to update their data.

This is partly related to #151 - we need a method of "creating" a new array from a supplied bit of data, and the current set.  Would love to know your thoughts here!
