### ISSUE TITLE
Ember Infinity on 2 or more nested routes

### ISSUE THREAD

**Issue by hhff** [hhff/ember-infinity#150]
@venkz identified a problem with using multiple instances of Ember Infinity on nested routes.

With a `parent/child` architecture, triggering a `loadMoreAction` on the parent route will be caught by the child route.  This is because Ember fires route actions from the most-active leaf of the router, rather than the corresponding route for the template.

This was unexpected behavior for me, and I'm still working around nice solution for Ember Infinity.

Would love to hear any thoughts here.

Wanted to open this here to track progress.

For Now, if you're doing this - please use this pattern:
https://github.com/hhff/ember-multi-infinity-scroll/commit/cfba20b78316266ea170136e8fd11a7813cc7b65

Related Issue:
https://github.com/emberjs/ember.js/issues/13288

**Comment by Blackening999** [comment]
Hey @hhff 
Very bad it hasn't been solved since April.
I think it's major issue, since it's ok to have content paginated with multiple infinity loads on the same page...

**Comment by hhff** [comment]
hi @Blackening999 - did you see the above pattern?  that solves the problem easily for now 👍 

As for "how bad it is" - please go ahead and submit a pull request!  It is "very bad" to complain about open-source without being constructive.  I posted the above stop-gap solution for the community to use in the meantime.

otherwise sit tight, someone will get to it eventually.

**Comment by Blackening999** [comment]
@hhff 
yep, I've checked the opportunity to call "private" method which works :)
hope will have time for PR since it's really easy thing to do.
Instead of using mixin - use a service, and make it mandatory to define the method for handling infinity load with further calling a public method on that service. The explicit method will allow to do any side-change during infinity load update.
The issue is, I don't think you'll want merge it since a lot of users already relies on mixin :\

**Comment by jimmay5469** [comment]
I pulled together a creative solution to fix the issue, check out #174 and let me know what you think. Thanks!
