### ISSUE TITLE
Load more button instead of infinite scrolling

### ISSUE THREAD

**Issue by dj-hedgehog** [hhff/ember-infinity#46]
On my homepage I've got a button to load more posts.
In order to upgrade to Ember 1.13 I'd like to switch to using ember-infinity but from what I've seen I won't be able to have a button like this without rewriting a lot of ember-infinity.

Do you have an idea how I could use ember-infinity nonetheless.

![image](https://cloud.githubusercontent.com/assets/7140800/8388658/0bedacd8-1c65-11e5-9b19-1fb199766547.png)

**Comment by hhff** [comment]
Oh you can use Ember Infinity like this out of the box.

Just setup everything as per the README, but instead of using the `infinity-loader` component, create your own component that sends the action `infinityLoad` when clicked.

In fact - I'd accept a PR to add a `buttonMode=true` attr to the `infinity-loader` component so that we can officially support this functionality

**Comment by dj-hedgehog** [comment]
Thanks a lot :)
I'm currently a little short on time because of my master thesis but will keep the PR in mind.

**Comment by hhff** [comment]
no worries!  i'll make an issue for it and hopefully get around to it soonish
