### ISSUE TITLE
Resetting the starting page?

### ISSUE THREAD

**Issue by b-d-b** [hhff/ember-infinity#91]
HHFF -- great work with this package, it's been really easy-breezy so far.  It's been working great at the basics, but I have run into an issue with a bound parameter and maybe I'm just doing it wrong.

I am passing a bound filter parameter called "year", and want to dynamically change which year I am looking at with a select.  I have successfully bound this parameter and it's doing what I expected with one slight caveat...

I default to 2015, which has 2 pages to load.  When I switch to 2014 and clear the store for my model (resetting the list, essentially) it loads the first page as page 2 of 2 instead of page 1 of 2 as a new set of pages to load from.

What is the best practice here?  Should I reload the page with a query parameter for year and just do it that way or is there a way to do it without a refresh by just resetting the startingPage parameter of the InfinityModel?

**Comment by b-d-b** [comment]
Here's the example code on a branch I forked from my repo if you're curious:

https://github.com/prowrestler-io/play.prowrestler.io/blob/example/app/routes/promotions/promotion/rosters.js

**Comment by b-d-b** [comment]
Looks like #90 is pretty close to what I need so I am gonna close this!

Much appreciation to the hard work being done on this to HHFF and cohorts :+1:

**Comment by DuBistKomisch** [comment]
I've been calling `this.refresh()` on the route, similar to #78 except run through `Ember.run.debounce` to prevent spamming the server as the user types. I also use an observer on the property instead of making it a query param. It seems to work as expected, and is smooth from the user perspective. It does internally trigger a route transition though unfortunately.

To be honest, when I first started implementing it, I assumed infinityModel would actually observe the bound properties, and automatically reset from page 1 when they change. Some documentation clarification on this whole area would be great.

**Comment by hhff** [comment]
a PR would be great @DuBistKomisch :+1:
